//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNOGui.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UNOGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string CampoContraseña {
            get {
                return ResourceManager.GetString("CampoContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string CampoCorreo {
            get {
                return ResourceManager.GetString("CampoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos incompletos.
        /// </summary>
        public static string CamposIncompletosTitulo {
            get {
                return ResourceManager.GetString("CamposIncompletosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string CampoUsuario {
            get {
                return ResourceManager.GetString("CampoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string CrearSala_ButonCrear {
            get {
                return ResourceManager.GetString("CrearSala_ButonCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese la contraseña de la sala..
        /// </summary>
        public static string CrearSala_CamposIncompletosMensaje {
            get {
                return ResourceManager.GetString("CrearSala_CamposIncompletosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Para cuántos jugadores es la sala?.
        /// </summary>
        public static string CrearSala_NumeroJugadores {
            get {
                return ResourceManager.GetString("CrearSala_NumeroJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea una sala para que juegues con tus amigos..
        /// </summary>
        public static string CrearSala_Subtitulo {
            get {
                return ResourceManager.GetString("CrearSala_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Idioma_Español {
            get {
                return ResourceManager.GetString("Idioma_Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string Idioma_Ingles {
            get {
                return ResourceManager.GetString("Idioma_Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string Inicio_Nivel {
            get {
                return ResourceManager.GetString("Inicio_Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje.
        /// </summary>
        public static string Inicio_Puntaje {
            get {
                return ResourceManager.GetString("Inicio_Puntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla de puntuaciones.
        /// </summary>
        public static string Inicio_TablaPuntaciones {
            get {
                return ResourceManager.GetString("Inicio_TablaPuntaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar juego.
        /// </summary>
        public static string Lobby_IniciarPartidaBoton {
            get {
                return ResourceManager.GetString("Lobby_IniciarPartidaBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicie la partida cuando haya al menos dos jugadores..
        /// </summary>
        public static string Lobby_MensajeHost {
            get {
                return ResourceManager.GetString("Lobby_MensajeHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere a que el host inicie la partida..
        /// </summary>
        public static string Lobby_MensajeInvitado {
            get {
                return ResourceManager.GetString("Lobby_MensajeInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir de sala.
        /// </summary>
        public static string Lobby_SalirBoton {
            get {
                return ResourceManager.GetString("Lobby_SalirBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de juego.
        /// </summary>
        public static string Lobby_Titulo {
            get {
                return ResourceManager.GetString("Lobby_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Login_IniciarSesion {
            get {
                return ResourceManager.GetString("Login_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string Login_RecuperarCuenta {
            get {
                return ResourceManager.GetString("Login_RecuperarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrate.
        /// </summary>
        public static string Login_Registrarse {
            get {
                return ResourceManager.GetString("Login_Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a u.
        /// </summary>
        public static string Login_SeperadorO {
            get {
                return ResourceManager.GetString("Login_SeperadorO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Mensaje_Buton {
            get {
                return ResourceManager.GetString("Mensaje_Buton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se cambió el idioma. Por favor, inicie sesión de nuevo..
        /// </summary>
        public static string Mensaje_CambioIdiomaMensaje {
            get {
                return ResourceManager.GetString("Mensaje_CambioIdiomaMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se cambió el idioma.
        /// </summary>
        public static string Mensaje_CambioIdiomaTitulo {
            get {
                return ResourceManager.GetString("Mensaje_CambioIdiomaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string MenuPrincipal_CerrarSesion {
            get {
                return ResourceManager.GetString("MenuPrincipal_CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala.
        /// </summary>
        public static string MenuPrincipal_CrearSala {
            get {
                return ResourceManager.GetString("MenuPrincipal_CrearSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string MenuPrincipal_Inicio {
            get {
                return ResourceManager.GetString("MenuPrincipal_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string MenuPrincipal_MiPerfil {
            get {
                return ResourceManager.GetString("MenuPrincipal_MiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola.
        /// </summary>
        public static string MenuPrincipal_Saludo {
            get {
                return ResourceManager.GetString("MenuPrincipal_Saludo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala.
        /// </summary>
        public static string MenuPrincipal_UnirseSala {
            get {
                return ResourceManager.GetString("MenuPrincipal_UnirseSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion.
        /// </summary>
        public static string MiPerfil_Configuracion {
            get {
                return ResourceManager.GetString("MiPerfil_Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string MiPerfil_Cuenta {
            get {
                return ResourceManager.GetString("MiPerfil_Cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experiencia.
        /// </summary>
        public static string MiPerfil_Experiencia {
            get {
                return ResourceManager.GetString("MiPerfil_Experiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string MiPerfil_GuardarCambios {
            get {
                return ResourceManager.GetString("MiPerfil_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string MiPerfil_Idioma {
            get {
                return ResourceManager.GetString("MiPerfil_Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego.
        /// </summary>
        public static string MiPerfil_Juego {
            get {
                return ResourceManager.GetString("MiPerfil_Juego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas ganadas.
        /// </summary>
        public static string MiPerfil_PartidasGanadas {
            get {
                return ResourceManager.GetString("MiPerfil_PartidasGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas jugadas.
        /// </summary>
        public static string MiPerfil_PartidasJugadas {
            get {
                return ResourceManager.GetString("MiPerfil_PartidasJugadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string MiPerfil_Titulo {
            get {
                return ResourceManager.GetString("MiPerfil_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese la clave y contraseña de la sala..
        /// </summary>
        public static string UnirseSala_CamposIncompletosMensaje {
            get {
                return ResourceManager.GetString("UnirseSala_CamposIncompletosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave de la sala.
        /// </summary>
        public static string UnirseSala_ClaveSala {
            get {
                return ResourceManager.GetString("UnirseSala_ClaveSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Únute a una sala para jugar con tus amigos..
        /// </summary>
        public static string UnirseSala_Subtitulo {
            get {
                return ResourceManager.GetString("UnirseSala_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirme.
        /// </summary>
        public static string UniseSala_BotonUnirse {
            get {
                return ResourceManager.GetString("UniseSala_BotonUnirse", resourceCulture);
            }
        }
    }
}
