//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNOGui.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UNOGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string CampoConfirmacionContraseña {
            get {
                return ResourceManager.GetString("CampoConfirmacionContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string CampoContraseña {
            get {
                return ResourceManager.GetString("CampoContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string CampoCorreo {
            get {
                return ResourceManager.GetString("CampoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string CampoNuevaContraseña {
            get {
                return ResourceManager.GetString("CampoNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa toda la información solicitada..
        /// </summary>
        public static string CamposIncompletosMensaje {
            get {
                return ResourceManager.GetString("CamposIncompletosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos incompletos.
        /// </summary>
        public static string CamposIncompletosTitulo {
            get {
                return ResourceManager.GetString("CamposIncompletosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string CampoUsuario {
            get {
                return ResourceManager.GetString("CampoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información invalida.
        /// </summary>
        public static string ContraseñasIncompatibles {
            get {
                return ResourceManager.GetString("ContraseñasIncompatibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string CrearSala_ButonCrear {
            get {
                return ResourceManager.GetString("CrearSala_ButonCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese la contraseña de la sala..
        /// </summary>
        public static string CrearSala_CamposIncompletosMensaje {
            get {
                return ResourceManager.GetString("CrearSala_CamposIncompletosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Para cuántos jugadores es la sala?.
        /// </summary>
        public static string CrearSala_NumeroJugadores {
            get {
                return ResourceManager.GetString("CrearSala_NumeroJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea una sala para que juegues con tus amigos..
        /// </summary>
        public static string CrearSala_Subtitulo {
            get {
                return ResourceManager.GetString("CrearSala_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, ocurrió un error en el servidor. Intente más tarde..
        /// </summary>
        public static string ErrorServidor_MensajeContenido {
            get {
                return ResourceManager.GetString("ErrorServidor_MensajeContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ups!.
        /// </summary>
        public static string ErrorServidor_TituloContenido {
            get {
                return ResourceManager.GetString("ErrorServidor_TituloContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Idioma_Español {
            get {
                return ResourceManager.GetString("Idioma_Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string Idioma_Ingles {
            get {
                return ResourceManager.GetString("Idioma_Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string Inicio_Nivel {
            get {
                return ResourceManager.GetString("Inicio_Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje.
        /// </summary>
        public static string Inicio_Puntaje {
            get {
                return ResourceManager.GetString("Inicio_Puntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla de puntuaciones.
        /// </summary>
        public static string Inicio_TablaPuntaciones {
            get {
                return ResourceManager.GetString("Inicio_TablaPuntaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar juego.
        /// </summary>
        public static string Lobby_IniciarPartidaBoton {
            get {
                return ResourceManager.GetString("Lobby_IniciarPartidaBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicie la partida cuando haya al menos dos jugadores..
        /// </summary>
        public static string Lobby_MensajeHost {
            get {
                return ResourceManager.GetString("Lobby_MensajeHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere a que el host inicie la partida..
        /// </summary>
        public static string Lobby_MensajeInvitado {
            get {
                return ResourceManager.GetString("Lobby_MensajeInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir de sala.
        /// </summary>
        public static string Lobby_SalirBoton {
            get {
                return ResourceManager.GetString("Lobby_SalirBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de juego.
        /// </summary>
        public static string Lobby_Titulo {
            get {
                return ResourceManager.GetString("Lobby_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Login_IniciarSesion {
            get {
                return ResourceManager.GetString("Login_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa tu usuario y contraseña para iniciar sesión..
        /// </summary>
        public static string Login_MensajeCamposContenido {
            get {
                return ResourceManager.GetString("Login_MensajeCamposContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos vacíos.
        /// </summary>
        public static string Login_MensajeCamposTitulo {
            get {
                return ResourceManager.GetString("Login_MensajeCamposTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor verifique la contraseña ingresada e intente de nuevo..
        /// </summary>
        public static string Login_MensajeContraseñaContenido {
            get {
                return ResourceManager.GetString("Login_MensajeContraseñaContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        public static string Login_MensajeContraseñaTitulo {
            get {
                return ResourceManager.GetString("Login_MensajeContraseñaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor verifique si el Nickname ingresado es correcto e intente de nuevo..
        /// </summary>
        public static string Login_MensajeNicknameContenido {
            get {
                return ResourceManager.GetString("Login_MensajeNicknameContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname incorrecto.
        /// </summary>
        public static string Login_MensajeNicknameTitulo {
            get {
                return ResourceManager.GetString("Login_MensajeNicknameTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encontramos que ya cuenta con una sesión iniciada. Verifique y cierre sesión..
        /// </summary>
        public static string Login_MensajeSesionIniciadaContenido {
            get {
                return ResourceManager.GetString("Login_MensajeSesionIniciadaContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión ya iniciada.
        /// </summary>
        public static string Login_MensajeSesionIniciadaTitulo {
            get {
                return ResourceManager.GetString("Login_MensajeSesionIniciadaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string Login_RecuperarCuenta {
            get {
                return ResourceManager.GetString("Login_RecuperarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrate.
        /// </summary>
        public static string Login_Registrarse {
            get {
                return ResourceManager.GetString("Login_Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a u.
        /// </summary>
        public static string Login_SeperadorO {
            get {
                return ResourceManager.GetString("Login_SeperadorO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Mensaje_Buton {
            get {
                return ResourceManager.GetString("Mensaje_Buton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se cambió el idioma. Por favor, inicie sesión de nuevo..
        /// </summary>
        public static string Mensaje_CambioIdiomaMensaje {
            get {
                return ResourceManager.GetString("Mensaje_CambioIdiomaMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se cambió el idioma.
        /// </summary>
        public static string Mensaje_CambioIdiomaTitulo {
            get {
                return ResourceManager.GetString("Mensaje_CambioIdiomaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string MenuPrincipal_CerrarSesion {
            get {
                return ResourceManager.GetString("MenuPrincipal_CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala.
        /// </summary>
        public static string MenuPrincipal_CrearSala {
            get {
                return ResourceManager.GetString("MenuPrincipal_CrearSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string MenuPrincipal_Inicio {
            get {
                return ResourceManager.GetString("MenuPrincipal_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string MenuPrincipal_MiPerfil {
            get {
                return ResourceManager.GetString("MenuPrincipal_MiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola.
        /// </summary>
        public static string MenuPrincipal_Saludo {
            get {
                return ResourceManager.GetString("MenuPrincipal_Saludo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala.
        /// </summary>
        public static string MenuPrincipal_UnirseSala {
            get {
                return ResourceManager.GetString("MenuPrincipal_UnirseSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion.
        /// </summary>
        public static string MiPerfil_Configuracion {
            get {
                return ResourceManager.GetString("MiPerfil_Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string MiPerfil_Cuenta {
            get {
                return ResourceManager.GetString("MiPerfil_Cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experiencia.
        /// </summary>
        public static string MiPerfil_Experiencia {
            get {
                return ResourceManager.GetString("MiPerfil_Experiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string MiPerfil_GuardarCambios {
            get {
                return ResourceManager.GetString("MiPerfil_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string MiPerfil_Idioma {
            get {
                return ResourceManager.GetString("MiPerfil_Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego.
        /// </summary>
        public static string MiPerfil_Juego {
            get {
                return ResourceManager.GetString("MiPerfil_Juego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas ganadas.
        /// </summary>
        public static string MiPerfil_PartidasGanadas {
            get {
                return ResourceManager.GetString("MiPerfil_PartidasGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas jugadas.
        /// </summary>
        public static string MiPerfil_PartidasJugadas {
            get {
                return ResourceManager.GetString("MiPerfil_PartidasJugadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string MiPerfil_Titulo {
            get {
                return ResourceManager.GetString("MiPerfil_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ganador de la partida es.
        /// </summary>
        public static string Partida_GanadorMensajeContenido {
            get {
                return ResourceManager.GetString("Partida_GanadorMensajeContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hay un ganador!.
        /// </summary>
        public static string Partida_GanadorMensajeTitulo {
            get {
                return ResourceManager.GetString("Partida_GanadorMensajeTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi puntaje.
        /// </summary>
        public static string Partida_MiPutaje {
            get {
                return ResourceManager.GetString("Partida_MiPutaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string Partida_NombreJugador {
            get {
                return ResourceManager.GetString("Partida_NombreJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Cartas.
        /// </summary>
        public static string Partida_NumeroCartas {
            get {
                return ResourceManager.GetString("Partida_NumeroCartas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje.
        /// </summary>
        public static string Partida_Puntaje {
            get {
                return ResourceManager.GetString("Partida_Puntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Partida_Salir {
            get {
                return ResourceManager.GetString("Partida_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno actual.
        /// </summary>
        public static string Partida_TurnoActual {
            get {
                return ResourceManager.GetString("Partida_TurnoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string RecuperacionCuenta_BotonCancelar {
            get {
                return ResourceManager.GetString("RecuperacionCuenta_BotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string RecuperacionCuenta_BotonConfirmar {
            get {
                return ResourceManager.GetString("RecuperacionCuenta_BotonConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingresa una nueva contraseña..
        /// </summary>
        public static string RecuperacionCuenta_Contenido {
            get {
                return ResourceManager.GetString("RecuperacionCuenta_Contenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recupera tu contraseña.
        /// </summary>
        public static string RecuperacionCuenta_Titulo {
            get {
                return ResourceManager.GetString("RecuperacionCuenta_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no son iguales.
        /// </summary>
        public static string RecuperacionDeCuenta_ContraseñasIncompatibles {
            get {
                return ResourceManager.GetString("RecuperacionDeCuenta_ContraseñasIncompatibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Registro_BotonCancelar {
            get {
                return ResourceManager.GetString("Registro_BotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string Registro_BotonRegistrar {
            get {
                return ResourceManager.GetString("Registro_BotonRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave de validación ingresada es incorrecta. Por favor, verifique la información..
        /// </summary>
        public static string Registro_ClaveInvalidaMensaje {
            get {
                return ResourceManager.GetString("Registro_ClaveInvalidaMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave de validación incorrecta.
        /// </summary>
        public static string Registro_ClaveInvalidaTitulo {
            get {
                return ResourceManager.GetString("Registro_ClaveInvalidaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ingresado pertenece ya a una cuenta. Por favor, ingrese uno diferente..
        /// </summary>
        public static string Registro_CorreoExisteMensaje {
            get {
                return ResourceManager.GetString("Registro_CorreoExisteMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ya existe.
        /// </summary>
        public static string Registro_CorreoExisteTitulo {
            get {
                return ResourceManager.GetString("Registro_CorreoExisteTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrado exitosamente. Inicia sesión para poder jugar con tus amigos..
        /// </summary>
        public static string Registro_ExitoMensaje {
            get {
                return ResourceManager.GetString("Registro_ExitoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro exitoso.
        /// </summary>
        public static string Registro_ExitoTitulo {
            get {
                return ResourceManager.GetString("Registro_ExitoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor verifica que las contraseñas ingresadas coincidan..
        /// </summary>
        public static string Registro_MensajeContraseñasContenido {
            get {
                return ResourceManager.GetString("Registro_MensajeContraseñasContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no son iguales.
        /// </summary>
        public static string Registro_MensajeContraseñasTitulo {
            get {
                return ResourceManager.GetString("Registro_MensajeContraseñasTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo generalmente se conforma por usuario@dominio. Ejemplos de dominio: gmail.com, hotmail.com, yahoo.com.
        /// </summary>
        public static string Registro_MensajeCorreoContenido {
            get {
                return ResourceManager.GetString("Registro_MensajeCorreoContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ingresado no es válido.
        /// </summary>
        public static string Registro_MensajeCorreoTitulo {
            get {
                return ResourceManager.GetString("Registro_MensajeCorreoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nickname ingresado ya existe. Por favor, ingrese otro diferente..
        /// </summary>
        public static string Registro_NicknameExisteMensaje {
            get {
                return ResourceManager.GetString("Registro_NicknameExisteMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nickname ya existe.
        /// </summary>
        public static string Registro_NicknameExisteTitulo {
            get {
                return ResourceManager.GetString("Registro_NicknameExisteTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te enviamos una nueva clave al correo especificado..
        /// </summary>
        public static string Registro_NuevaClaveMensaje {
            get {
                return ResourceManager.GetString("Registro_NuevaClaveMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave de validación enviada.
        /// </summary>
        public static string Registro_NuevaClaveTituloMensaje {
            get {
                return ResourceManager.GetString("Registro_NuevaClaveTituloMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar cuenta.
        /// </summary>
        public static string Registro_Titulo {
            get {
                return ResourceManager.GetString("Registro_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string RegistroEnEspera_CancelarBoton {
            get {
                return ResourceManager.GetString("RegistroEnEspera_CancelarBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No recibiste la clave de validación?.
        /// </summary>
        public static string RegistroEnEspera_ClaveNoRecibida {
            get {
                return ResourceManager.GetString("RegistroEnEspera_ClaveNoRecibida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave de validación.
        /// </summary>
        public static string RegistroEnEspera_ClaveValidacion {
            get {
                return ResourceManager.GetString("RegistroEnEspera_ClaveValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar registro.
        /// </summary>
        public static string RegistroEnEspera_ConfirmarBoton {
            get {
                return ResourceManager.GetString("RegistroEnEspera_ConfirmarBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ya casi terminamos!.
        /// </summary>
        public static string RegistroEnEspera_ContenidoTitulo {
            get {
                return ResourceManager.GetString("RegistroEnEspera_ContenidoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar de nuevo.
        /// </summary>
        public static string RegistroEnEspera_EnviarDeNuevoBoton {
            get {
                return ResourceManager.GetString("RegistroEnEspera_EnviarDeNuevoBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te enviamos una clave de validación al correo especificado para que confirmes tu registro. Por favor, ingresala en el siguiente campo..
        /// </summary>
        public static string RegistroEnEspera_Mensaje {
            get {
                return ResourceManager.GetString("RegistroEnEspera_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro en espera.
        /// </summary>
        public static string RegistroEnEspera_VentanaTitulo {
            get {
                return ResourceManager.GetString("RegistroEnEspera_VentanaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar de nuevo en.
        /// </summary>
        public static string Temporizador_Mensaje {
            get {
                return ResourceManager.GetString("Temporizador_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese la clave y contraseña de la sala..
        /// </summary>
        public static string UnirseSala_CamposIncompletosMensaje {
            get {
                return ResourceManager.GetString("UnirseSala_CamposIncompletosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave de la sala.
        /// </summary>
        public static string UnirseSala_ClaveSala {
            get {
                return ResourceManager.GetString("UnirseSala_ClaveSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Únute a una sala para jugar con tus amigos..
        /// </summary>
        public static string UnirseSala_Subtitulo {
            get {
                return ResourceManager.GetString("UnirseSala_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirme.
        /// </summary>
        public static string UniseSala_BotonUnirse {
            get {
                return ResourceManager.GetString("UniseSala_BotonUnirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de recuperación.
        /// </summary>
        public static string VerificarCodigo_Campo {
            get {
                return ResourceManager.GetString("VerificarCodigo_Campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te enviamos un código de recuperación a su dirección de correo. Por favor, ingreselo en el siguiente campo..
        /// </summary>
        public static string VerificarCodigo_Contenido {
            get {
                return ResourceManager.GetString("VerificarCodigo_Contenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No recibiste el código de recuperación?.
        /// </summary>
        public static string VerificarCodigo_Pregunta {
            get {
                return ResourceManager.GetString("VerificarCodigo_Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar de nuevo.
        /// </summary>
        public static string VerificarCodigo_Reenvio {
            get {
                return ResourceManager.GetString("VerificarCodigo_Reenvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar código.
        /// </summary>
        public static string VerificarCodigo_Titulo {
            get {
                return ResourceManager.GetString("VerificarCodigo_Titulo", resourceCulture);
            }
        }
    }
}
