//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNO.AccesoADatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Jugador
    {
        public string Nickname { get; set; }
        public string CorreoElectronico { get; set; }
        public string Contraseña { get; set; }
        public Nullable<int> Experiencia { get; set; }
        public Nullable<int> PuntajeTotal { get; set; }
        public Nullable<int> PartidasGanadas { get; set; }
        public Nullable<int> PartidasJugadas { get; set; }
        public int Nivel { get; set; }
    }
}
